import os
import contextlib
from textual.app import ComposeResult
from textual.widgets import Label, Input, Button, RichLog
from textual.worker import Worker, WorkerState

from gpatcher.ia.client import invoke_upload
from gpatcher.tui_screens.base import BaseFormScreen, TextualLogRedirector

class UploadPatchScreen(BaseFormScreen):
    title_text = "Upload Patch to Internet Archive"
    submit_label = "Upload Patch"

    def compose_form(self) -> ComposeResult:
        yield Label("Local Patch ZIP file Path:")
        yield Input(placeholder="e.g. D:/patches/hades_v1.0-to-v1.2.patch.zip", id="patch-input")
        yield Label("Creator Name:")
        yield Input(value="anonymous", placeholder="e.g. anonymous", id="creator-input")
        yield Label("Description:")
        yield Input(value="Game patch generated by gpatcher", placeholder="Description metadata", id="desc-input")

    def submit_form(self) -> None:
        patch = self.query_one("#patch-input", Input).value.strip().strip('"').strip("'")
        creator = self.query_one("#creator-input", Input).value.strip()
        desc = self.query_one("#desc-input", Input).value.strip()

        log_widget = self.query_one("#console-log", RichLog)
        status_label = self.query_one("#status-label", Label)

        if not patch or not os.path.exists(patch):
            log_widget.write(f"[err] Local patch file not found: {patch}\n")
            return

        patch_abs = os.path.abspath(os.path.expanduser(patch))

        self.query_one("#btn-submit", Button).disabled = True
        self.query_one("#btn-cancel", Button).disabled = True
        log_widget.write("Starting upload worker thread...\n")

        def bg_task():
            redirector = TextualLogRedirector(log_widget, status_label)
            with contextlib.redirect_stdout(redirector):
                invoke_upload(patch_abs, creator=creator, description=desc)

        def on_complete(worker: Worker):
            self.query_one("#btn-submit", Button).disabled = False
            self.query_one("#btn-cancel", Button).disabled = False
            status_label.update("")
            if worker.state == WorkerState.SUCCESS:
                log_widget.write("[ok] Upload completed successfully!\n")
            elif worker.state == WorkerState.ERROR:
                log_widget.write(f"[err] Upload failed: {worker.error}\n")

        self.run_worker(bg_task, thread=True, on_status_change=lambda e: self.handle_worker_status(e, on_complete))
